CREATE EXTENSION IF NOT EXISTS ltree;

CREATE TABLE refs (
    code VARCHAR(8) PRIMARY KEY,
    path LTREE NOT NULL,
    points INT NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
)

CREATE INDEX idx_refs_path ON refs USING GIST (path);
